"""user model

Revision ID: d24f185b8a54
Revises: 953a03c8d326
Create Date: 2025-05-10 19:29:18.985000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d24f185b8a54"
down_revision: Union[str, None] = "953a03c8d326"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("disabled", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("role", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.drop_column("users", "disabled")
    # ### end Alembic commands ###
